language: r
cache: packages 

r:
  - release
  - devel

before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev

install:
  - R --vanilla -e 'install.packages("rmarkdown")'
  
script: 
  - R --vanilla -e 'rmarkdown::render("./using-spatialwarnings.Rmd")'
