language: r
cache: packages 

r:
  - release
  - devel

before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev

install:
  - R -e 'install.packages("rmarkdown", repos = "https://cloud.r-project.org")'
  
script: 
  - R -e 'rmarkdown::render("./using-spatialwarnings.Rmd")'
